const questions = [
  {
    type: "radiogroup",
    name: "bike",
    title: "What bike are you riding?",
    isRequired: true,
    colCount: 4,
    choices: ["BMW", "Bajaj", "HarleyDavidson", "Yamaha", "Jawa"],
  },
  {
    type: "radiogroup",
    name: "food",
    title: "What food do you like to eat",
    isRequired: true,
    colCount: 4,
    choices: ["Biriyani", "Fried-Rice", "paulou", "Veg-Biriyani", "Curd-Rice"],
  },
  {
    type: "radiogroup",
    name: "Phone",
    title: "Which company phone would you like to buy?",
    isRequired: true,
    colCount: 2,
    choices: ["Apple", "One-Plus", "Xiomi", "Moto", "Nokia"],
  },
  {
    type: "radiogroup",
    name: "Phone",
    title: "Which company phone would you like to buy?",
    isRequired: true,
    colCount: 2,
    choices: ["Apple", "One-Plus", "Xiomi", "Moto", "Nokia"],
  },
  {
    type: "radiogroup",
    name: "Phone",
    title: "Which company phone would you like to buy?",
    isRequired: true,
    colCount: 2,
    choices: ["Apple", "One-Plus", "Xiomi", "Moto", "Nokia"],
  },
  {
    type: "radiogroup",
    name: "Phone",
    title: "Which company phone would you like to buy?",
    isRequired: true,
    colCount: 2,
    choices: ["Apple", "One-Plus", "Xiomi", "Moto", "Nokia"],
  },]